services:
   silverstripe:
      image: brettt89/silverstripe-web:8.3-apache
      volumes:
         - ./app:/var/www/html
      depends_on:
         - database
      ports:
         - 8080:80
      environment:
         - DOCUMENT_ROOT=/var/www/html/public
         - SS_TRUSTED_PROXY_IPS=*
         - SS_ENVIRONMENT_TYPE=dev
         - SS_DATABASE_SERVER=database
         - SS_DATABASE_NAME=haushalt
         - SS_DATABASE_USERNAME=haushalt
         - SS_DATABASE_PASSWORD=haushalt
         - SS_DEFAULT_ADMIN_USERNAME=admin
         - SS_DEFAULT_ADMIN_PASSWORD=password

   database:
      image: mysql:8.0
      environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=haushalt
         - MYSQL_USER=haushalt
         - MYSQL_PASSWORD=haushalt
      ports:
           - 3306:3306
      volumes:
         - db-data:/var/lib/mysql

   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      depends_on:
         - database
      ports:
         - 8081:80
      environment:
         - PMA_HOST=database
         - PMA_USER=haushalt
         - PMA_PASSWORD=haushalt
         - PMA_ARBITRARY=1

volumes:
      db-data: